CREATE TABLE IF NOT EXISTS tblPasswordResetTokens (
  TokenID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  TokenHash VARCHAR(64) NOT NULL,     -- sha256 hex
  ExpiresAt DATETIME NOT NULL,
  UsedAt DATETIME NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (UserID),
  INDEX (TokenHash),
  CONSTRAINT fk_reset_user FOREIGN KEY (UserID) REFERENCES tblusers(UserID) ON DELETE CASCADE
);
