USE Rawson;

CREATE TABLE IF NOT EXISTS tblUserProofs (
        ProofID INT AUTO_INCREMENT PRIMARY KEY,
        UserID INT NOT NULL,
        FilePath VARCHAR(255) NOT NULL,
        Address VARCHAR(255) DEFAULT NULL,
        UploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_userproofs_user FOREIGN KEY (UserID) REFERENCES tblusers(UserID)
          ON DELETE CASCADE ON UPDATE CASCADE
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;