USE Rawson;

-- Add geo columns to properties (idempotent checks)
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tblProperties' AND COLUMN_NAME='PlaceId');
SET @sql := IF(@col=0, 'ALTER TABLE tblProperties ADD COLUMN PlaceId VARCHAR(128) NULL AFTER PostalCode', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tblProperties' AND COLUMN_NAME='Latitude');
SET @sql := IF(@col=0, 'ALTER TABLE tblProperties ADD COLUMN Latitude DECIMAL(9,6) NULL AFTER PlaceId', 'SELECT 1'); PREPARE s2 FROM @sql; EXECUTE s2; DEALLOCATE PREPARE s2;

SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tblProperties' AND COLUMN_NAME='Longitude');
SET @sql := IF(@col=0, 'ALTER TABLE tblProperties ADD COLUMN Longitude DECIMAL(9,6) NULL AFTER Latitude', 'SELECT 1'); PREPARE s3 FROM @sql; EXECUTE s3; DEALLOCATE PREPARE s3;

-- Helpful indexes
SET @idx := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tblProperties' AND INDEX_NAME='idx_properties_placeid');
SET @sql := IF(@idx=0, 'CREATE INDEX idx_properties_placeid ON tblProperties (PlaceId)', 'SELECT 1'); PREPARE s4 FROM @sql; EXECUTE s4; DEALLOCATE PREPARE s4;

-- Add geo columns to users
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tblusers' AND COLUMN_NAME='PlaceId');
SET @sql := IF(@col=0, 'ALTER TABLE tblusers ADD COLUMN PlaceId VARCHAR(128) NULL AFTER Phone', 'SELECT 1'); PREPARE s5 FROM @sql; EXECUTE s5; DEALLOCATE PREPARE s5;

SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tblusers' AND COLUMN_NAME='Latitude');
SET @sql := IF(@col=0, 'ALTER TABLE tblusers ADD COLUMN Latitude DECIMAL(9,6) NULL AFTER PlaceId', 'SELECT 1'); PREPARE s6 FROM @sql; EXECUTE s6; DEALLOCATE PREPARE s6;

SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tblusers' AND COLUMN_NAME='Longitude');
SET @sql := IF(@col=0, 'ALTER TABLE tblusers ADD COLUMN Longitude DECIMAL(9,6) NULL AFTER Latitude', 'SELECT 1'); PREPARE s7 FROM @sql; EXECUTE s7; DEALLOCATE PREPARE s7;

-- Optional indexes
SET @idx := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tblusers' AND INDEX_NAME='idx_users_placeid');
SET @sql := IF(@idx=0, 'CREATE INDEX idx_users_placeid ON tblusers (PlaceId)', 'SELECT 1'); PREPARE s8 FROM @sql; EXECUTE s8; DEALLOCATE PREPARE s8;

ALTER TABLE tblproperties MODIFY COLUMN PlaceId VARCHAR(64) NULL;

ALTER TABLE tblusers MODIFY COLUMN PlaceId VARCHAR(64) NULL;