USE Rawson;

DESCRIBE tblTickets;

-- Also check the allowed values for enums
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'Rawson' AND TABLE_NAME = 'tblTickets' AND COLUMN_NAME = 'CurrentStatus';